main: com.arodsg.speedruntimer.Main
name: Speedrun-Timer
version: 1.0
author: arodSG
description: Timer/Stopwatch plugin for tracking time during a speedrun
commands:
   srt:
      description: commands for Speedrun Timer plugin
      usage: /srt [enable/disable]
      aliases: [speedruntimer, timer]
      permission: speedruntimer.srt
      permission-message: You don't have the speedruntimer.srt permission.