main: com.arodsg.hardcoretimer.Main
name: Hardcore-Timer
version: 1.0
author: arodSG
description: Timer/Stopwatch plugin for tracking time during a hardcore run
commands:
   hct:
      description: commands for Hardcore Timer plugin
      usage: /hct [enable/disable]
      alias: [hardcoretimer]
      permission: hardcoretimer.hct
      permission-message: You don't have the hardcoretimer.hct permission.